In [1]:
%pip install numpy

def homework(message):
    print("\n>>>>>", message, "\n")

import numpy as np

# Початковий список температур
temperature = [20.1, 20.1, 20.2, 20.4]
print("Початковий список температур:", temperature)

# Множення списку на число
t1 = temperature * 5
print(f"При множенні списку на 5 маємо: {t1}")
homework("Множення списку на число дублює сам список, а не елементи в ньому. Це пов'язано з тим, як Python обробляє операцію множення для списків. У результаті список повторюється п'ять разів.")

# Множення кожного елемента списку на 5
t1 = [x * 5 for x in temperature]
print(f"Тепер отримаємо множення кожного елемента: {t1}")
homework("Тут використовується list comprehension. Оператор `x * 5` виконує множення кожного елемента списку, тому результат відрізняється від попереднього.")

# Перетворення списку у NumPy масив
t2 = np.array(temperature)
print("Масив з використанням NumPy:", t2)

# Множення NumPy масиву на число
t3 = t2 * 5
print("При множенні NumPy масиву на 5 отримуємо:", t3)
homework("NumPy дозволяє виконувати векторизовані операції. Коли NumPy масив множиться на число, це означає, що операція виконується для кожного елемента масиву.")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.0/16.0 MB 65.2 MB/s eta 0:00:00:00:01
Note: you may need to restart the kernel to use updated packages.
Початковий список температур: [20.1, 20.1, 20.2, 20.4]
При множенні списку на 5 маємо: [20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4]

>>>>> Множення списку на число дублює сам список, а не елементи в ньому. Це пов'язано з тим, як Python обробляє операцію множення для списків. У результаті список повторюється п'ять разів. 

Тепер отримаємо множення кожного елемента: [100.5, 100.5, 101.0, 102.0]

>>>>> Тут використовується list comprehension. Оператор `x * 5` виконує множення кожного елемента списку, тому результат відрізняється від попереднього. 

Масив з використанням NumPy: [20.1 20.1 20.2 20.4]
При множенні NumPy масиву на 5 отримуємо: [100.5 100.5 101.  102. ]

>>>>> NumPy дозволяє виконувати векторизовані операції. Коли NumPy масив множиться на число, це означ

In [2]:
import numpy as np

# Генерація масивів
start = 5
size_of_vec = 100

# Масиви через range та np.arange
x = range(size_of_vec)
a = np.arange(size_of_vec)
print(f"Масив згенерований простим range: {list(x)[:5]} та методом arange: {a[:5]}")
homework("Весь діапазон чисел з range та arange:\nRange: {}\nArange: {}".format(list(x), a))

# Задаємо початок генерації
a = np.arange(start, size_of_vec)
print(f"Можемо задавати початок генерації вектора, перший елемент: {a[0]}")
homework(f"Останній діапазон у згенерованому масиві: {a[-1]}")

x = range(start, size_of_vec)
print("Те саме але з вбудованою функцією range:", x)
print("Власне вивід значень:", list(x)[0])
homework(f"Число з середини діапазону: {list(x)[len(x)//2]}")

# Дробові числа
x = np.arange(10.4)
print("Будем мати:", x)

# Крок 0.5
x = np.arange(0.5, 4, 0.5)
print("З кроком 0.5:", x)

# Крок 0.08
x = np.arange(0.04, 1.84, 0.08)
print("З кроком 0.08:", x, "\n Зверніть увагу на заокруглення")
homework("Згенеровані значення з кроком 0.08: {}".format(x))

# Генерація з кроком, що має чотири нулі після коми
x = np.arange(0.0001, 1.0001, 0.0001)
print("З кроком 0.0001:", x)
homework("Згенеровані значення з кроком 0.0001: {}".format(x))

# Операції з отриманими числами
y = x * 2.5
print("Після перемноження:", y)
homework(f"Піднесення до степеня (y**2) та ділення на 0.4:\n{y**2 / 0.4}")

Масив згенерований простим range: [0, 1, 2, 3, 4] та методом arange: [0 1 2 3 4]

>>>>> Весь діапазон чисел з range та arange:
Range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
Arange: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] 

Можемо задавати початок генерації вектора, перший елемент: 5

>>>>> Останній діапазон у згенерованому масиві: 99 

Те саме але з вбудованою функцією range: ran

In [3]:
import numpy as np

# Згенерувати числовий діапазон
start = 5
size_of_vec = 100

# Генерація з використанням linspace
a = np.linspace(start, size_of_vec)
print(f"Згенерувала {len(a)} чисел в діапазоні {a[0]} до {a[-1]}")

# Вивести кожне друге число згенерованого діапазону за допомогою циклу
homework("Кожне друге число:")
for i in range(1, len(a), 2):  # крок 2
    print(a[i], end=" ")

print("\n\nМожна зменшити кількість чисел до 5:")
a = np.linspace(start, size_of_vec, 5)
print(a)
homework("Збільшую кількість чисел до 100 і виведу перші та останні 10:")
a = np.linspace(start, size_of_vec, 100)
print(f"Перші 10 чисел: {a[:10]}")
print(f"Останні 10 чисел: {a[-10:]}")

# Виключення останнього значення
print("""
Перше та останнє значення завжди входять у згенерований діапазон. 
Відповідно при цьому вираховується крок.
Це можна змінити, виключивши останнє значення з визначення діапазону.
""")
print(np.linspace(start, size_of_vec, 5, endpoint=False))
homework("Крок числового ряду, коли останнє значення виключено:")
step = (size_of_vec - start) / 5
print(f"Крок (вручну): {step}")

# Порівняння автоматичного визначення кроку
_, sp_1 = np.linspace(start, size_of_vec, 5, endpoint=True, retstep=True)
_, sp_2 = np.linspace(start, size_of_vec, 5, endpoint=False, retstep=True)
print(f"Для порівняння, визначу крок автоматично, у нашому випадку це {sp_1} (з endpoint=True) та {sp_2} (з endpoint=False)")

homework(f"Крок з endpoint=True: {sp_1}, крок з endpoint=False: {sp_2}. Різниця пояснюється тим, що з `endpoint=False` останнє число виключено з розрахунку, тому крок більший.")

Згенерувала 50 чисел в діапазоні 5.0 до 100.0

>>>>> Кожне друге число: 

6.938775510204081 10.816326530612244 14.693877551020408 18.57142857142857 22.448979591836736 26.3265306122449 30.20408163265306 34.08163265306122 37.95918367346939 41.83673469387755 45.714285714285715 49.59183673469388 53.46938775510204 57.3469387755102 61.224489795918366 65.10204081632654 68.9795918367347 72.85714285714286 76.73469387755102 80.61224489795919 84.48979591836735 88.36734693877551 92.24489795918367 96.12244897959184 100.0 

Можна зменшити кількість чисел до 5:
[  5.    28.75  52.5   76.25 100.  ]

>>>>> Збільшую кількість чисел до 100 і виведу перші та останні 10: 

Перші 10 чисел: [ 5.          5.95959596  6.91919192  7.87878788  8.83838384  9.7979798
 10.75757576 11.71717172 12.67676768 13.63636364]
Останні 10 чисел: [ 91.36363636  92.32323232  93.28282828  94.24242424  95.2020202
  96.16161616  97.12121212  98.08080808  99.04040404 100.        ]

Перше та останнє значення завжди входять у згенеро

In [4]:
import numpy as np

# Приклади масивів різної розмірності
examples = {
    'Скаляр': np.array(1), 
    'Вектор Рядок': np.array([1, 2, 3]), 
    'Вектор Стовпець': np.array([[1], [2], [3]]), 
    'Матриця': np.array([[1, 2], [3, 4], [5, 6]]),
    'Багатовимірна Матриця': np.array([[[111, 112], [121, 122]],
                                        [[211, 212], [221, 222]],
                                        [[311, 312], [321, 322]]])
}

# Виведення інформації для кожного прикладу
for key in examples:
    print(f"Розглядаємо приклад з {key}. \nЗначення x буде: \n", examples[key])
    print(f"Тип {key} x: ", type(examples[key]))
    print(f"Розмірність/вимір {key} x:", np.ndim(examples[key]))
    print(f"Форма {key} x: ", examples[key].shape)
    print(f"Кількість елементів х: {np.size(examples[key])}")
    print("-=-" * 10)

# Пояснення результату
homework("""Функція np.ndim повертає кількість вимірів масиву (rank). 
Вектор-рядок та вектор-стовпець мають однакову розмірність 1D (один вимір), тому np.ndim повертає 1 для обох. 
Форма (shape) вказує кількість елементів у кожному вимірі: наприклад, (3,) для рядка та (3, 1) для стовпця. 
Це значення shape пояснює відмінність між вектором-рядком і вектором-стовпцем.""")

# Завдання: Задайте власні вектори
my_vector_row = np.array([10, 20, 30, 40])
my_vector_column = np.array([[10], [20], [30], [40]])

print("Мій вектор-рядок:\n", my_vector_row)
print("Розмірність:", np.ndim(my_vector_row))
print("Форма:", my_vector_row.shape)

print("Мій вектор-стовпець:\n", my_vector_column)
print("Розмірність:", np.ndim(my_vector_column))
print("Форма:", my_vector_column.shape)

Розглядаємо приклад з Скаляр. 
Значення x буде: 
 1
Тип Скаляр x:  <class 'numpy.ndarray'>
Розмірність/вимір Скаляр x: 0
Форма Скаляр x:  ()
Кількість елементів х: 1
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Вектор Рядок. 
Значення x буде: 
 [1 2 3]
Тип Вектор Рядок x:  <class 'numpy.ndarray'>
Розмірність/вимір Вектор Рядок x: 1
Форма Вектор Рядок x:  (3,)
Кількість елементів х: 3
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Вектор Стовпець. 
Значення x буде: 
 [[1]
 [2]
 [3]]
Тип Вектор Стовпець x:  <class 'numpy.ndarray'>
Розмірність/вимір Вектор Стовпець x: 2
Форма Вектор Стовпець x:  (3, 1)
Кількість елементів х: 3
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Матриця. 
Значення x буде: 
 [[1 2]
 [3 4]
 [5 6]]
Тип Матриця x:  <class 'numpy.ndarray'>
Розмірність/вимір Матриця x: 2
Форма Матриця x:  (3, 2)
Кількість елементів х: 6
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Багатовимірна Матриця. 
Значення x буде: 
 [[[111 112]
  [121 122]]

 [[211 

In [5]:
import numpy as np

# Початкові приклади
examples = {
    '5 рядків': np.array([[1], [2], [3], [4], [5]]), 
    '5 стовпців': np.array([[1, 2, 3, 4, 5]]),
    '5 елементів у вкладеному масиві': np.array([[[1, 2, 3, 4, 5]]])
}

# Виведення shape та вигляду
for a in examples:
    print(f"Для {a} маю shape: {examples[a].shape}\nта вигляд:\n{examples[a]}")
    print("-" * 30)

# Власні масиви
my_arrays = {
    '1D масив (рядок)': np.array([10, 20, 30]),
    '2D масив (матриця)': np.array([[10, 20], [30, 40], [50, 60]]),
    '3D масив (куб)': np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]),
    '4D масив': np.array([[[[1, 2], [3, 4]]]])
}

# Виведення власних прикладів
for b in my_arrays:
    print(f"Для {b} маю shape: {my_arrays[b].shape}\nта вигляд:\n{my_arrays[b]}")
    print("-" * 30)

homework("Використовуючи метод `shape`, можна легко визначати виміри та структуру масивів. Це особливо корисно для аналізу багатовимірних даних у математиці, статистиці чи машинному навчанні.")

Для 5 рядків маю shape: (5, 1)
та вигляд:
[[1]
 [2]
 [3]
 [4]
 [5]]
------------------------------
Для 5 стовпців маю shape: (1, 5)
та вигляд:
[[1 2 3 4 5]]
------------------------------
Для 5 елементів у вкладеному масиві маю shape: (1, 1, 5)
та вигляд:
[[[1 2 3 4 5]]]
------------------------------
Для 1D масив (рядок) маю shape: (3,)
та вигляд:
[10 20 30]
------------------------------
Для 2D масив (матриця) маю shape: (3, 2)
та вигляд:
[[10 20]
 [30 40]
 [50 60]]
------------------------------
Для 3D масив (куб) маю shape: (2, 2, 2)
та вигляд:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
------------------------------
Для 4D масив маю shape: (1, 1, 2, 2)
та вигляд:
[[[[1 2]
   [3 4]]]]
------------------------------

>>>>> Використовуючи метод `shape`, можна легко визначати виміри та структуру масивів. Це особливо корисно для аналізу багатовимірних даних у математиці, статистиці чи машинному навчанні. 



In [6]:
import numpy as np

# Масив Фібоначчі
F = np.array([1, 1, 2, 3, 5, 8, 13, 21])

print(f"""Масив: {F}
Виміри: {F.shape}
Пам'ятаємо, що індексація масивів починається з 0.
Тому перший елемент масиву:\n {F[0]}
Другий:\n {F[1]}
Останній елемент (за довжиною масиву {len(F)}): \n {F[7]}""")

print(f"""Можемо скористатись від'ємними індексами, якщо хочемо доступитися до елементів з кінця масиву.
Тоді останній елемент:\n {F[-1]}
Передостанній:\n {F[-2]}""")

# Практика з доступом до елементів
homework("Практикую доступ до елементів:")
print(f"Третій елемент масиву: {F[2]}")
print(f"П'ятий елемент масиву: {F[4]}")
print(f"Елемент за індексом 6: {F[6]}")

# Доступ до елементів за зрізами
print(f"Перші три елементи масиву: {F[:3]}")  # Зріз від початку до третього елемента (не включно)
print(f"Елементи з 3-го по 6-й: {F[2:6]}")    # Зріз із 3-го по 6-й елемент
print(f"Останні три елементи масиву: {F[-3:]}")  # Зріз трьох останніх елементів

# Доступ до елементів за кроком
print(f"Кожний другий елемент масиву: {F[::2]}")  # Зріз із кроком 2
print(f"Масив у зворотному порядку: {F[::-1]}")   # Зворотний порядок

Масив: [ 1  1  2  3  5  8 13 21]
Виміри: (8,)
Пам'ятаємо, що індексація масивів починається з 0.
Тому перший елемент масиву:
 1
Другий:
 1
Останній елемент (за довжиною масиву 8): 
 21
Можемо скористатись від'ємними індексами, якщо хочемо доступитися до елементів з кінця масиву.
Тоді останній елемент:
 21
Передостанній:
 13

>>>>> Практикую доступ до елементів: 

Третій елемент масиву: 2
П'ятий елемент масиву: 5
Елемент за індексом 6: 13
Перші три елементи масиву: [1 1 2]
Елементи з 3-го по 6-й: [2 3 5 8]
Останні три елементи масиву: [ 8 13 21]
Кожний другий елемент масиву: [ 1  2  5 13]
Масив у зворотному порядку: [21 13  8  5  3  2  1  1]


In [7]:
import numpy as np

# Вихідний масив
A = np.array([[3.4, 8.7, 9.9], 
              [1.1, -7.8, -0.7],
              [4.1, 12.3, 4.8],
              [7.0, -3.9, 5.1]])

# Виведення початкової інформації
print(f"""Масив:
{A}
Виміри: {A.shape}
Принцип номерації ТІЛЬКИ:
Якщо задати одне значення, то отримаємо цілий рядок:
    Перший рядок: {A[0]}
    Останній рядок: {A[-1]}
Для вибору стовпця (символ ':' вказує на вибір усіх елементів):
    Перший стовпець: {A[:, 0]}
    Останній стовпець: {A[:, -1]}
Для вибору конкретного елемента треба два індекси:
    Перший елемент: {A[0, 0]}
    Останній елемент: {A[-1, -1]}
""")

# Завдання: виведення елементів, які належать діагоналі
homework("Ппрактикуюсь в доступі до багатовимірного масиву, виводити елементи, які належать діагоналі.")

# Діагональні елементи
main_diagonal = [A[i, i] for i in range(min(A.shape))]
print(f"Елементи головної діагоналі: {main_diagonal}")

# Виведення елементів побічної діагоналі
secondary_diagonal = [A[i, -i-1] for i in range(min(A.shape))]
print(f"Елементи побічної діагоналі: {secondary_diagonal}")

# Додаткові зрізи
print(f"Головна діагональ за допомогою np.diagonal(): {np.diagonal(A)}")
print(f"Побічна діагональ за допомогою np.fliplr(A).diagonal(): {np.fliplr(A).diagonal()}")

Масив:
[[ 3.4  8.7  9.9]
 [ 1.1 -7.8 -0.7]
 [ 4.1 12.3  4.8]
 [ 7.  -3.9  5.1]]
Виміри: (4, 3)
Принцип номерації ТІЛЬКИ:
Якщо задати одне значення, то отримаємо цілий рядок:
    Перший рядок: [3.4 8.7 9.9]
    Останній рядок: [ 7.  -3.9  5.1]
Для вибору стовпця (символ ':' вказує на вибір усіх елементів):
    Перший стовпець: [3.4 1.1 4.1 7. ]
    Останній стовпець: [ 9.9 -0.7  4.8  5.1]
Для вибору конкретного елемента треба два індекси:
    Перший елемент: 3.4
    Останній елемент: 5.1


>>>>> Ппрактикуюсь в доступі до багатовимірного масиву, виводити елементи, які належать діагоналі. 

Елементи головної діагоналі: [np.float64(3.4), np.float64(-7.8), np.float64(4.8)]
Елементи побічної діагоналі: [np.float64(9.9), np.float64(-7.8), np.float64(4.1)]
Головна діагональ за допомогою np.diagonal(): [ 3.4 -7.8  4.8]
Побічна діагональ за допомогою np.fliplr(A).diagonal(): [ 9.9 -7.8  4.1]


In [8]:
import numpy as np

# Вихідний масив
S = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Виведення початкової інформації
print(f"""Масив:
{S}
Виміри: {S.shape}
Беремо декілька елементів: {S[2:5]}
Всі елементи до заданого: {S[:4]}
Всі елементи від заданого до кінця: {S[6:]}
Всі елементи: {S[:]}
""")

# Завдання: виведення останніх 4 елементів масиву
homework("Практикуюсь у витягуванні елементів, беру 4 значення з кінця масиву.")
last_four = S[-4:]

Масив:
[0 1 2 3 4 5 6 7 8 9]
Виміри: (10,)
Беремо декілька елементів: [2 3 4]
Всі елементи до заданого: [0 1 2 3]
Всі елементи від заданого до кінця: [6 7 8 9]
Всі елементи: [0 1 2 3 4 5 6 7 8 9]


>>>>> Практикуюсь у витягуванні елементів, беру 4 значення з кінця масиву. 



In [9]:
import numpy as np

# Вихідний масив
A = np.array([
    [11, 12, 13, 14, 15],
    [21, 22, 23, 24, 25],
    [31, 32, 33, 34, 35],
    [41, 42, 43, 44, 45],
    [51, 52, 53, 54, 55]
])

# Виведення початкової інформації
print(f"""Масив:
{A}
Виміри: {A.shape}
Беремо декілька рядків: 
{A[0:2]}
Два перші стовпці: 
{A[:, 0:2]}
Два останні рядки:
{A[3:, :]}
Беремо підматрицю (нижні елементи): 
{A[-3:, -3:]}
""")

# Завдання: Витягуємо підматриці 2х2
homework("Практикуюсь у витягуванні елементів, беру матрицю 2х2 з нижнього та верхнього кутка матриці A.")

# Верхній лівий кут
top_left = A[:2, :2]
print(f"Підматриця 2х2 із верхнього лівого кута:\n{top_left}")

# Нижній правий кут
bottom_right = A[-2:, -2:]
print(f"Підматриця 2х2 із нижнього правого кута:\n{bottom_right}")

Масив:
[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]
 [51 52 53 54 55]]
Виміри: (5, 5)
Беремо декілька рядків: 
[[11 12 13 14 15]
 [21 22 23 24 25]]
Два перші стовпці: 
[[11 12]
 [21 22]
 [31 32]
 [41 42]
 [51 52]]
Два останні рядки:
[[41 42 43 44 45]
 [51 52 53 54 55]]
Беремо підматрицю (нижні елементи): 
[[33 34 35]
 [43 44 45]
 [53 54 55]]


>>>>> Практикуюсь у витягуванні елементів, беру матрицю 2х2 з нижнього та верхнього кутка матриці A. 

Підматриця 2х2 із верхнього лівого кута:
[[11 12]
 [21 22]]
Підматриця 2х2 із нижнього правого кута:
[[44 45]
 [54 55]]


In [10]:
import numpy as np

# Створюємо масив
A = np.arange(28).reshape(4, 7)

# Виводимо початкову інформацію
print(f"""Масив:
{A}
Виміри: {A.shape}
Беремо кожен другий елемент першого рядка: 
{A[0, ::2]}
Беремо кожен третій елемент першого рядка: 
{A[0, ::3]}
Кожен другий елемент у кожному другому рядку: 
{A[::2, ::2]}
Останні три елементи в кожному другому рядку:
{A[::2, 4:]}
Можна повністю змінити порядок елементів (дзеркально обернемо):
{A[::-1, ::-1]}
""")

# Завдання: Попрактикуйтесь у витягуванні елементів
homework("Практикуюсь у витягуванні елементів, будь-яка робоча комбінація.")

# Комбінації витягування
# Центральна частина матриці
center = A[1:3, 2:5]
print(f"Центральна частина матриці (2x3):\n{center}")

# Четвертий елемент кожного рядка
fourth_elements = A[:, 3]
print(f"Четвертий елемент кожного рядка:\n{fourth_elements}")

# Рядки в зворотному порядку
reversed_rows = A[::-1, :]
print(f"Рядки в зворотному порядку:\n{reversed_rows}")

# Перші три рядки та кожен другий елемент
subset = A[:3, ::2]
print(f"Перші три рядки, кожен другий елемент:\n{subset}")

Масив:
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]
Виміри: (4, 7)
Беремо кожен другий елемент першого рядка: 
[0 2 4 6]
Беремо кожен третій елемент першого рядка: 
[0 3 6]
Кожен другий елемент у кожному другому рядку: 
[[ 0  2  4  6]
 [14 16 18 20]]
Останні три елементи в кожному другому рядку:
[[ 4  5  6]
 [18 19 20]]
Можна повністю змінити порядок елементів (дзеркально обернемо):
[[27 26 25 24 23 22 21]
 [20 19 18 17 16 15 14]
 [13 12 11 10  9  8  7]
 [ 6  5  4  3  2  1  0]]


>>>>> Практикуюсь у витягуванні елементів, будь-яка робоча комбінація. 

Центральна частина матриці (2x3):
[[ 9 10 11]
 [16 17 18]]
Четвертий елемент кожного рядка:
[ 3 10 17 24]
Рядки в зворотному порядку:
[[21 22 23 24 25 26 27]
 [14 15 16 17 18 19 20]
 [ 7  8  9 10 11 12 13]
 [ 0  1  2  3  4  5  6]]
Перші три рядки, кожен другий елемент:
[[ 0  2  4  6]
 [ 7  9 11 13]
 [14 16 18 20]]


In [11]:
import numpy as np

# Створення масиву
A = np.arange(50)

# Умова для парних чисел
all_even = (A % 2 == 0)

# Комплексна умова для вибору чисел
complex_condition = (A < 30) & (A / 5 < 2)

# Виведення результатів
print(f"""Спочатку потрібно створити умову за якою здійснювати вибірку.
Результат умови буде або {all_even[0]} для {A[0]} або {all_even[1]} для {A[1]}.
Після підставляння умови пошуку парних чисел в масив отримаємо:
{A[all_even]}
Або застосувавти більш комплексну умову з двох порівнянь:
{A[complex_condition]}
""")

# Завдання: Вивести всі непарні числа з масиву
homework("Виведжу всі непарні числа з даного масиву.")

# Умова для непарних чисел (які не є парними)
all_odd = (A % 2 != 0)

# Виведення непарних чисел
print(f"Непарні числа в масиві: {A[all_odd]}")

Спочатку потрібно створити умову за якою здійснювати вибірку.
Результат умови буде або True для 0 або False для 1.
Після підставляння умови пошуку парних чисел в масив отримаємо:
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
Або застосувавти більш комплексну умову з двох порівнянь:
[0 1 2 3 4 5 6 7 8 9]


>>>>> Виведжу всі непарні числа з даного масиву. 

Непарні числа в масиві: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [13]:
import numpy as np
a = np.arange(1, 55, 2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53]


In [14]:
import numpy as np
b = np.linspace(1, 10, 5)
print(b)

[ 1.    3.25  5.5   7.75 10.  ]


In [18]:
import numpy as np

# Створюю вектор-рядок та вектор-стовпець
vector_row = np.array([8, 5, 8, 4, 5])
vector_column = np.array([[1], [2], [3], [4], [5]])

# Створюю матрицю 2x3
matrix_2x3 = np.array([[1, 9, 3], [4, 4, 6]])

# Створюю матрицю 3x3
matrix_3x3 = np.array([[7, 6, 9], [10, 16, 12], [14, 14, 15]])

# Виводжу розмірність
print("Розмірність вектора-рядка:", vector_row.shape)
print("Розмірність вектора-стовпця:", vector_column.shape)
print("Розмірність матриці 2x3:", matrix_2x3.shape)
print("Розмірність матриці 3x3:", matrix_3x3.shape)

Розмірність вектора-рядка: (5,)
Розмірність вектора-стовпця: (5, 1)
Розмірність матриці 2x3: (2, 3)
Розмірність матриці 3x3: (3, 3)


In [20]:
# Додавання векторів
vector_add = vector_row + np.array([1, 8, 1, 9, 1])
print("\nДодавання векторів:\n", vector_add)

# Множення вектора на скаляр
vector_multiply = vector_row * 2
print("\nМноження вектора на скаляр:\n", vector_multiply)

# Віднімання векторів
vector_subtract = vector_row - np.array([0, 4, 9, 3, 1])
print("\nВіднімання векторів:\n", vector_subtract)


Додавання векторів:
 [ 9 13  9 13  6]

Множення вектора на скаляр:
 [16 10 16  8 10]

Віднімання векторів:
 [ 8  1 -1  1  4]
